version: '3'
services:
  apollo_universal_starter_scala:
    image: hseeberger/scala-sbt
    container_name: apollo_universal_starter_scala
      working_dir: ${APP_DIR}/packages
      command: ${BACKEND_RUN_COMMAND:-sbt -jvm-debug 9999 run}
      volumes:
      - scala-backend-app-folder:${APP_DIR}
      - ./app:${APP_DIR}/app
      - ./conf:${APP_DIR}/conf
      - ./project/build.properties:${APP_DIR}/project/build.properties
      - ./project/plugins.sbt:${APP_DIR}/project/plugins.sbt
      - ./test:${APP_DIR}/test
      - ./public:${APP_DIR}/public
      - ./build.sbt:${APP_DIR}/build.sbt

      - scala-backend-sbt-cache:/root/.ivy2
      ports:
      - 9000:9000
      - 9999:9999
      stdin_open: true
      tty: true

volumes:
  scala-backend-sbt-cache:
  scala-backend-app-folder: